/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MensagensIndexRouteImport } from './routes/mensagens.index'
import { Route as MensagensChatIdRouteImport } from './routes/mensagens.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensIndexRoute = MensagensIndexRouteImport.update({
  id: '/mensagens/',
  path: '/mensagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensChatIdRoute = MensagensChatIdRouteImport.update({
  id: '/mensagens/$chatId',
  path: '/mensagens/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/feed': typeof FeedRoute
  '/loja': typeof LojaRoute
  '/perfil': typeof PerfilRoute
  '/mensagens/$chatId': typeof MensagensChatIdRoute
  '/mensagens/': typeof MensagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/feed': typeof FeedRoute
  '/loja': typeof LojaRoute
  '/perfil': typeof PerfilRoute
  '/mensagens/$chatId': typeof MensagensChatIdRoute
  '/mensagens': typeof MensagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/feed': typeof FeedRoute
  '/loja': typeof LojaRoute
  '/perfil': typeof PerfilRoute
  '/mensagens/$chatId': typeof MensagensChatIdRoute
  '/mensagens/': typeof MensagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bem-vindo'
    | '/feed'
    | '/loja'
    | '/perfil'
    | '/mensagens/$chatId'
    | '/mensagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bem-vindo'
    | '/feed'
    | '/loja'
    | '/perfil'
    | '/mensagens/$chatId'
    | '/mensagens'
  id:
    | '__root__'
    | '/'
    | '/bem-vindo'
    | '/feed'
    | '/loja'
    | '/perfil'
    | '/mensagens/$chatId'
    | '/mensagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BemVindoRoute: typeof BemVindoRoute
  FeedRoute: typeof FeedRoute
  LojaRoute: typeof LojaRoute
  PerfilRoute: typeof PerfilRoute
  MensagensChatIdRoute: typeof MensagensChatIdRoute
  MensagensIndexRoute: typeof MensagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/': {
      id: '/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof MensagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/$chatId': {
      id: '/mensagens/$chatId'
      path: '/mensagens/$chatId'
      fullPath: '/mensagens/$chatId'
      preLoaderRoute: typeof MensagensChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BemVindoRoute: BemVindoRoute,
  FeedRoute: FeedRoute,
  LojaRoute: LojaRoute,
  PerfilRoute: PerfilRoute,
  MensagensChatIdRoute: MensagensChatIdRoute,
  MensagensIndexRoute: MensagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
